[package]
name = "staking-meta"
version = "0.0.0"
edition = "2021"
publish = true
authors = [ "René Ďuriš"]

[dev-dependencies]

[dependencies.staking]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.38.0"
