// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           18
// Async Callback (empty):               1
// Total number of exported functions:  20

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    staking
    (
        changeAPR
        supplyRewards
        stakeTokens
        UnstakeTokens
        claim
        reinvest
        reward
        totalStaked
        suppliedRewards
        storageRewards
        stakedAmount
        stakedPosition
        RPSAcumulated
        Token
        APR
        lockTime
        unlockTime
        APRLastTime
    )
}

elrond_wasm_node::wasm_empty_callback! {}
